### ISSUE TITLE
[Git bash][Windows]

### ISSUE THREAD

**Issue by HauklandJ** [JeanJouliaCode/wipeClean#9]
$ npm install wipeclean -g
$ wipeclean

index.js:62
  const startPoint = { x: closestStartPoint.x, y: rows - verticalMargin }
                                            ^

TypeError: Cannot read property 'x' of undefined
    at getRectangularPath (file:///C:/Users/JohannesHaukland/AppData/Roaming/npm/node_modules/wipeclean/index.js:62:45)
    at startDrawing (file:///C:/Users/JohannesHaukland/AppData/Roaming/npm/node_modules/wipeclean/index.js:15:26)
    at file:///C:/Users/JohannesHaukland/AppData/Roaming/npm/node_modules/wipeclean/index.js:169:1
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

**Comment by HauklandJ** [comment]
Works in cmd, but not in git bash
